### ISSUE TITLE
测试了一下，魅族16th开启失败

### ISSUE THREAD

**Issue by JRICKL** [Tomotoes/scrcpy-gui#1]
无论有线还是无线，配置啥的应该配置成功了，点击开启无线连接后，软件上显示倒是打开成功，手机屏幕也亮了一下，就是没有画面🤣🤣🤣

**Comment by Tomotoes** [comment]
那不应该啊...

如果 adb scrcpy 都配置成功了..
您可以从命令行试一下..

查看现在连接的所有设备
adb devices

adb connect ip地址
举例: adb connect 192.167.0.100:5555

关闭一切无线连接
adb disconnect

如果当前只有一个设备连接, 可以直接使用 
scrcpy
打开手机

如果有多个连接, 可以使用
scrcpy -s id (有线连接的id号)
或者
scrcpy -s ip地址
打开设备

如果您可以在命令行打开设备..
那么就是我软件的问题了... 不是scrcpy的问题..

我昨天一直再用小米设备测试 😭

谢谢您的反馈~ 






------------------------------------------------------------------
发件人：JRICKL <notifications@github.com>
发送时间：2019年8月26日(星期一) 17:21
收件人：Tomotoes/scrcpy-gui <scrcpy-gui@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[Tomotoes/scrcpy-gui] 测试了一下，魅族16th开启失败 (#1)

无论有线还是无线，配置啥的应该配置成功了，点击开启无线连接后，软件上显示倒是打开成功，手机屏幕也亮了一下，就是没有画面🤣🤣🤣

**Comment by JRICKL** [comment]
应该不是你软件的问题，我手机命令行也不能成功打开，具体问题我去看了，是这个
https://github.com/Genymobile/scrcpy/issues/613

**Comment by ZerOri** [comment]
不是你的操作有误，个人猜测是魅族手机的flyme修改了安卓底层支持环境导致scrcpy失效

**Comment by ZerOri** [comment]
> 那不应该啊... 如果 `adb` ,`scrcpy` 都配置成功了.. 您可以从命令行试一下.. 1. 查看现在连接的所有设备 `adb devices` 2. 连接无线设备 `adb connect ip地址` 举例: adb connect 192.167.0.100:5555 3. 关闭一切无线连接 `adb disconnect` 如果当前只有一个设备连接, 可以直接使用 `scrcpy` 打开手机 如果有多个连接, 可以使用 `scrcpy -s id (有线连接的id号)` 或者 `scrcpy -s ip地址`打开设备 如果您可以在命令行打开设备.. 那么就是我软件的问题了... 不是scrcpy的问题.. 我昨天一直再用小米设备测试 😭 谢谢您的反馈~

哈哈，你也是小米9用户

**Comment by JRICKL** [comment]
> 不是你的操作有误，个人猜测是魅族手机的flyme修改了安卓底层支持环境导致scrcpy失效

是这样的，flame魔改Android
