### ISSUE TITLE
小米MAX 小米MIX2S 打开失败 

### ISSUE THREAD

**Issue by zero19902005** [Tomotoes/scrcpy-gui#10]
## Feature request
小米MAX
小米MIX2S 打开失败 

显示
Info
正在打开镜像,请稍等片刻...
Error
设备ID 打开失败,请您仔细查阅帮助文档

命令符显示
child process close all stdio with code Error: spawn scrcpy ENOENT
child process close all stdio with code -4058

**Comment by Tomotoes** [comment]
你可以使用命令行打开吗？

**Comment by zero19902005** [comment]
scrcpy.exe 这个可以正常打开使用
