### ISSUE TITLE
手机开启屏幕时gui点选打开镜像关闭屏幕时电脑上的镜像无法完成手机解锁

### ISSUE THREAD

**Issue by erge6521** [Tomotoes/scrcpy-gui#110]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 红米k30s
2. MIUI 12.02
3. scrcpy 版本：1.7
4. 是否可以使用 scrcpy 在命令行 打开设备：可以
5. 手机开启屏幕时gui点选打开镜像关闭屏幕时电脑上的镜像无法完成手机解锁

**Comment by Tomotoes** [comment]
目前是这样的，暂时不支持。
