### ISSUE TITLE
是否可以实现安卓客户端？

### ISSUE THREAD

**Issue by catcherxuefeng** [Tomotoes/scrcpy-gui#117]
需求
一台安卓手机控制另一台安卓手机

**Comment by Ayx03** [comment]
这个项目只是给Scrcpy一个界面而已，一台安卓手机控制另一台可以尝试TeamViewer/向日葵（收费功能）

**Comment by catcherxuefeng** [comment]
> 这个项目只是给Scrcpy一个界面而已，一台安卓手机控制另一台可以尝试TeamViewer/向日葵（收费功能）

是这样的，TeamViewer/向日葵是跨公网的，我是打算通过局域网进行控制（我的手机屏幕碎了，目前在用win版本的 scrcpy-gui 进行操作但是这样无法外出携带）
