### ISSUE TITLE
使用后的反馈建议

### ISSUE THREAD

**Issue by xyoye** [Tomotoes/scrcpy-gui#19]
首先很感谢您开发的这个GUI，它让我免除了使用命令操作的麻烦。

使用后有一些建议：

1. 相关提示的出现位置，最经常出现的情况就是我改变了镜像配置，点击保存出现保存成功的通知，这时我返回镜像管理，就会出现需要手动关闭通知的情况，感觉操作不流畅，建议通知能否变更一下形式，类似与Android手机在中下方显示半透明通知，或者将当前通知位置稍微往下挪一点。

2. 能否增加两套或多套镜像配置，如有线和无线各一套。目前我遇到的情况时，无线的配置与有线连接的配置差别较大，每次切换都会比较麻烦。

再次感谢您开发的GUI，以上仅是我使用后的一些个人感觉，暂未考虑时间及技术成本，希望这些建议不会给您带来困扰。

**Comment by Tomotoes** [comment]
感谢您的提议~

我已加入项目的roadmap ...

第一点 很简单, 第二点 需要一些时间..

不过由于目前学业繁重, 并准备考研, 所以一直抽不出时间来开发.. 

望见谅~

(等到国庆, 应该就有时间了...)
