### ISSUE TITLE
坚果R1开启失败

### ISSUE THREAD

**Issue by tchangeme** [Tomotoes/scrcpy-gui#2]
坚果R1无法使用，提示错误

**Comment by tchangeme** [comment]
使用命令行可以正常打开

**Comment by Tomotoes** [comment]
请问提示错误具体是什么呢? 
错误场景具体是什么呢?
您的操作系统是什么?

如果可以正常连接无线模式, 但是一打开镜像, 就提示 `{name }打开失败,请您仔细查阅帮助文档`
那么就说明, scrcpy 是可以打开设备的..

很有可能 原因在于, 我使用的是 node 原生的进程API `spwan` 来开启进程...  会存在某些故障

**Comment by tchangeme** [comment]
正如你所说"如果可以正常连接无线模式，但是一打开镜像，就提示{name }打开失败,请您仔细查阅帮助文档
那么就说明，scrcpy是可以打开设备的.."
