### ISSUE TITLE
开启无线连接  在电脑端延迟大。  切有卡顿。

### ISSUE THREAD

**Issue by ixinshang** [Tomotoes/scrcpy-gui#20]
## 所需信息
1. 一加3T  使用MIUI10
2. miui10
3. scrcpy scrcpy-win64-v1.10
4. 是否可以使用 scrcpy 在命令行 打开设备    :  可以
5. 使用网络打开的速度比接USB口慢很多。  请问是否有特殊需要手动修改的地方。 
之前使用scrcpy 命令行打开网络调试，和USB接线测试无明显差异。

最后，感谢开发。

**Comment by Tomotoes** [comment]
是不是由于 比特率的配置 呢?
建议您切换不同的比特率...

**Comment by ixinshang** [comment]
> 是不是由于 比特率的配置 呢?
> 建议您切换不同的比特率...

已经设置成1024了，无明显变化。
之前使用命令行，我都是设置3M。 目前这个软件的话，手动我测试了一下，最大只能到1024.

**Comment by arbaleast** [comment]
同卡顿，比特率2m 分辨率1080P，不定时卡死
