### ISSUE TITLE
魅蓝S6无法正常打开镜像

### ISSUE THREAD

**Issue by Droid-MAX** [Tomotoes/scrcpy-gui#21]
## 前置需求
可以全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型
魅蓝S6
2. 系统信息
Android 7.0, Flyme 7.2.0.0A
3. scrcpy 版本
1.10
4. 是否可以使用 scrcpy 在命令行 打开设备
No
5. 出错信息
INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
D:\ScrcpyGui\bin\scrcpy-server.jar: 1 file pushed. 2.4 MB/s (22546 bytes in 0.009s)
INFO: Initial texture: 720x1440

**Comment by Tomotoes** [comment]
好像是因为魅族手机的问题
