### ISSUE TITLE
显示成功启动，但实际未启动的问题

### ISSUE THREAD

**Issue by ly1n** [Tomotoes/scrcpy-gui#22]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型
HUAWEI 8X
2. 系统信息
V 9.1
3. scrcpy 版本
V1.10
4. 是否可以使用 scrcpy 在命令行 打开设备
无法直接打开，需要加上-m参数，如：scrcpy -m 1920
5. 出错信息
GUI显示成功打开，但实际未打开

![图片](https://user-images.githubusercontent.com/17906006/65575565-a682fc00-df5f-11e9-97a5-5f21e962c5c0.png)
![图片](https://user-images.githubusercontent.com/17906006/65575627-cf0af600-df5f-11e9-8aa4-d11a454b5562.png)

**Comment by ly1n** [comment]
GUI上没有启动配置选项，无法设定启动尺寸大小。

**Comment by Tomotoes** [comment]
有的 max-size 最大尺寸 就是 -m。
你配置一下再试试。

**Comment by ly1n** [comment]
> 
> 
> 有的 max-size 最大尺寸 就是 -m。
> 你配置一下再试试。

scrcpy可以设置，但在GUI上如何设置呢？配置界面只有剪切显示屏的设置

**Comment by Tomotoes** [comment]
您加下qq群吧

**Comment by Tomotoes** [comment]
gui上面有的啊

**Comment by ly1n** [comment]
> 
> 
> gui上面有的啊

![图片](https://user-images.githubusercontent.com/17906006/65596616-c24dc880-df86-11e9-9eef-98a33347f318.png)
我尝试了下，如果从命令行开启，可以设置。但GUI上我不知道能通过什么方式修改
