### ISSUE TITLE
【建议功楞】建议加入可以访问广域网或者域名访问的功楞~

### ISSUE THREAD

**Issue by xuhan999** [Tomotoes/scrcpy-gui#24]
路由大致是
家里的安卓设备（有内网唯一固定IP）→路由器端口转发（内网穿透与避开ISP端口封锁）→动态域名（保证共用IP不变）→→PC客户端
这样在家用带宽足够的情况下也能远程操作了！
现在是输入IP的地方不资瓷输入域名……希望能添加这样的功楞！程序用的很舒服！很好用！

**Comment by Tomotoes** [comment]
呃， 该软件的定位是为 Scrcpy 提供 GUI ， 您说的估计无法完成...
