### ISSUE TITLE
Deepin 15.11 打开后是白板界面

### ISSUE THREAD

**Issue by richwxd** [Tomotoes/scrcpy-gui#25]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型 
2. 系统信息
3. scrcpy 版本 1.1
4. 是否可以使用 scrcpy 在命令行 打开设备
5. 出错信息 ： 应该不是scrcpy问题，命令行下可以使用，但是gui的界面打开时白板

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by supdo** [comment]
在deepin15.12下打开也是白板。

**Comment by Tomotoes** [comment]
原因在于我， 打包成 linux 应用后， 没有在相应的环境下进行测试...

**Comment by Tomotoes** [comment]
您可以 clone 下项目, rebuild 下, 问题应该会解决.
