### ISSUE TITLE
关于调用scrcpy的建议

### ISSUE THREAD

**Issue by CescMessi** [Tomotoes/scrcpy-gui#26]
由于本身我的电脑安装了Android Studio，环境变量里用的是Android SDK里的adb，和scrcpy里的adb版本不同，会产生冲突，所以我使用scrcpy时是先进入它的目录再使用的。所以我想gui程序里能不能加个选项设定scrcpy的目录，这样也免去设置环境变量的麻烦。

**Comment by Tomotoes** [comment]
完全可以的， 我已加入 TODO， thanks.

**Comment by peaksea** [comment]
无线连不上 奇怪不知道哪里配置不对

**Comment by MccallisterJ** [comment]
Heres how I get around the ADB version difference on windows
*-open notepad and paste the following -edit resolution/fullscreen to your liking and "x's" with your info-*

@echo off echo
adb kill-server
adb start-server
adb connect 192.168.1.xx
scrcpy -m1920 --f

*-save as "whatever".cmd in scrcpy file folder-* 
*-double-click and profit-*

**Comment by inoribea** [comment]
> Heres how I get around the ADB version difference on windows
> _-open notepad and paste the following -edit resolution/fullscreen to your liking and "x's" with your info-_
> 
> @echo off echo
> adb kill-server
> adb start-server
> adb connect 192.168.1.xx
> scrcpy -m1920 --f
> 
> _-save as "whatever".cmd in scrcpy file folder-_
> _-double-click and profit-_



> Heres how I get around the ADB version difference on windows
> _-open notepad and paste the following -edit resolution/fullscreen to your liking and "x's" with your info-_
> 
> @echo off echo
> adb kill-server
> adb start-server
> adb connect 192.168.1.xx
> scrcpy -m1920 --f
> 
> _-save as "whatever".cmd in scrcpy file folder-_
> _-double-click and profit-_

Thank you very much.
this way can resolve win10‘s can not use by no PATH, because ScrcpyGui looks like has not make a key for connect android ADB.

如果win10出现打开后出现成功提示但不显示画面可通过这位朋友的方法解决。

**Comment by inoribea** [comment]
> 无线连不上 奇怪不知道哪里配置不对

看我下面的方法
