### ISSUE TITLE
文件拖放和共享剪切板无效，我使用的是win10企业版本，比如我在计算机上复制了一段中文文字，然后粘贴到手机浏览器地址栏无法实现，但是数字符号英文可以复制成功。但是如果数字符号中如果出现中文只会复制除了中文之外的东西，从计算机上把一个记事本文件或者apk文件拖进窗口也无法实现复制和安装功能。我使用的是有线投屏方式。谢谢！

### ISSUE THREAD

**Issue by 11fen** [Tomotoes/scrcpy-gui#27]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型
2. 系统信息
3. scrcpy 版本
4. 是否可以使用 scrcpy 在命令行 打开设备
5. 出错信息

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by Tomotoes** [comment]
建议您加一下 QQ 群： 734330215
您的问题 应该是 adb 软件的问题， 不好解决。
