### ISSUE TITLE
能否支持坚果R1，三星，华为的大屏模式呢？

### ISSUE THREAD

**Issue by tchangeme** [Tomotoes/scrcpy-gui#3]
可以通过一线通接上一个HDMI的欺骗器，启动大屏模式后，在通过无线的方式或其他方式连接到锤子坚果的TNT或三星的DEX模式，那就太牛了。现在有太多人为了使用大屏模式，买了触控屏，但也有很多人喜欢大屏模式，比如TNT，但是已经有笔记本或PC了，如果能用这种方式解决，应该还是很有市场的。

**Comment by Tomotoes** [comment]
嗯嗯, 听起来很有趣~

具体是需要实现什么样子的需求呢...

我没有大屏设备, 脑补不到您的场景... sorry

**Comment by tchangeme** [comment]
当手机的typec接口 连上一个hdmi接口的欺骗器之后，实际上启动了2个系统。一个是原生的手机界面，一个是大屏的桌面模式

**Comment by tchangeme** [comment]
现在华为、三星、魅族等都有支持大屏模式的手机

**Comment by tchangeme** [comment]
目前，要是想启用大屏模式，需要一根typec 到typec的连接线，直接接到带type c 接口的显示屏上，就可以自动启动大屏模式。
或者是用一个typec 转hdmi 的扩展坞，后就可以启动大屏模式
但是局限是，必须通过线材接到显示器、显示屏或者电视机上之后，才可以用
要是可以用scrcpy的投屏模式，无线投屏到笔记本或台式机上，那就方便很多。
现在很多人，为了使用桌面模式，都会话800-1600左右专门买一个触控的显示屏，在加上蓝牙键鼠去体验。
成本很高，并且对于那些已经由电脑的用户，需要额外花费费用，并且当两个系统切换时，很麻烦。

**Comment by tchangeme** [comment]
https://m.youtube.com/watch?v=6Cpy15kZMyg&t=745s#menu
可以参考这个视频了解
