### ISSUE TITLE
Android10 关闭手机屏幕的功能异常

### ISSUE THREAD

**Issue by CDN18** [Tomotoes/scrcpy-gui#30]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型：OnePlus 7 Pro
2. 系统信息:Hydrogen OS 10.0.0.GM21(稳定版)，Android 10
3. scrcpy 版本：1.0.0
4. 是否可以使用 scrcpy 在命令行 打开设备：是
5. 出错信息：
勾选后通过有线连接投屏 无法实现手机屏幕关闭，且电脑控制失效，但屏幕能正常刷新

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by Tomotoes** [comment]
我觉得应该是 USB调试那里， 你没有选择打开 电脑控制手机选项吧。。
我的Miui 有。。

**Comment by Tomotoes** [comment]
建议加一下 QQ 群： 734330215
