### ISSUE TITLE
MIUI 11 打开镜像是黑屏，但是电脑可以控制手机

### ISSUE THREAD

**Issue by zxzx8388** [Tomotoes/scrcpy-gui#31]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型  mi6
2. 系统信息  miui11
3. 是否可以使用 scrcpy 在命令行 打开设备，可以
4. 出错信息   镜像是黑屏，但是可以通过电脑控制手机，升级miui11之后才出现，之前可以使用

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information  mi6
2. System information    miui11
3. scrcpy version  1.0.0.0
4. Is it possible to open the device on the command line using scrcpy?   yes
5. Error message   when open mirror, it shows black screen, but PC can control Phone through the mirror, it happened when phone system update to MIUI 11, scrcpy can be used normally before.

**Comment by Tomotoes** [comment]
首先建议 您进一下 ScrcpyGUI 的 QQ 群：734330215。

最近群里的网友也反映过 您的问题，我觉得是 MIUI11 的问题， 具体的解决方案 目前还没有。
