### ISSUE TITLE
arch 安装tar包提示缺少元数据

### ISSUE THREAD

**Issue by linlinlin1992** [Tomotoes/scrcpy-gui#32]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型
2. 系统信息
manjaro系统 arch
3. scrcpy 版本
1.10-2
4. 是否可以使用 scrcpy 在命令行 打开设备
5. 出错信息
下载tar包用pacman安装时提示
错误：/home/lin/下载/ScrcpyGui-1.0.0.tar.xz 中缺少软件包元数据
错误：'/home/lin/下载/ScrcpyGui-1.0.0.tar.xz': 无效或已损坏的软件包

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by Tomotoes** [comment]
linux 版本并没有测试..

**Comment by SamLukeYes** [comment]
这是源码包吧，不是 pacman 的软件包
