### ISSUE TITLE
小米max3 投屏成功 无法控制

### ISSUE THREAD

**Issue by createskyblue** [Tomotoes/scrcpy-gui#39]
1. MI MAX 3
2. MIUI 11.0.3 电脑端win10
3. scrcpy 版本
4. 可以使用 scrcpy 在命令行 打开设备
5. 无法控制手机 已确保电脑控制手机的选项开启

**Comment by createskyblue** [comment]
解决措施：
1.确保开发者模式中，usb调试开启，usb调试（安全设置）开启
2.倘若无法开启无线控制，需要通过数据线连接手机，打开命令提示符，通过adb连接手机后执行adb tcpip 5555，即可解决问题

**Comment by optdesigns** [comment]
有个usb调试（安全设置）打开它才能控制

**Comment by kiccd4g** [comment]
> 

打开该选项需要 先登陆小米账号
