### ISSUE TITLE
scrcpy-gui window is empty (Ubuntu 19.04)

### ISSUE THREAD

**Issue by logix2** [Tomotoes/scrcpy-gui#4]
I'm using Ubuntu 19.04, and I installed scrcrpy-gui using the .deb. When launching the application, its window is completely empty, with no error message shown (and no terminal output).

**Comment by Tomotoes** [comment]
I'm sorry, I haven't tested the linux system yet. Most likely, it's a electron builder configuration problem .

**Comment by ShuiHuo** [comment]
Arch linux 使用 releases 里面的 ScrcpyGui-1.0.0.tar.xz，没有任何字符输出，显示了一个空白的窗口。

**Comment by Tomotoes** [comment]
> Arch linux 使用 releases 里面的 ScrcpyGui-1.0.0.tar.xz，没有任何字符输出，显示了一个空白的窗口。

估计就是打包的问题..
由于没有 linux 环境.. so 打包之后的程序没有测试..

你可以把项目 clone 下来, 在根目录执行 npm run start 打开软件...
