### ISSUE TITLE
连接成功但是没有出现投屏界面

### ISSUE THREAD

**Issue by geekyouth** [Tomotoes/scrcpy-gui#44]
## 前置需求
可全局使用 scrcpy adb 命令
adb --version
Android Debug Bridge version 1.0.41
Version 29.0.2-5738569

scrcpy --version
scrcpy 1.10

dependencies:
 - SDL 2.0.10
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100

## 所需信息
1. 手机类型
荣耀20pro 
2. 系统信息
安卓10，magic ui 3.0.0
3. scrcpy 版本
1.1.0
4. 是否可以使用 scrcpy 在命令行 打开设备
可以投屏

5. 出错信息
gui 提示已成功打开xxx，但是没有弹出投屏界面
![image](https://user-images.githubusercontent.com/12899262/75688065-c3271b00-5cd9-11ea-8438-c6e366ef33b7.png)

**Comment by Tomotoes** [comment]
可能是您的账户没有足够的权限, 后端无法创建进程.

**Comment by zjwon** [comment]
我在Mac上也出现了这个问题，但是直接使用scrcpy的命令是可以正常投屏的，如果是权限问题的话，该如何设置scrcpy-gui的权限呢

**Comment by dreamcastddr** [comment]
我也遇见了相同问题

**Comment by chengwerit** [comment]
我是在scrcpy上usb连接可以投屏，无线可以连接上，投屏失败，请问是什么原因。在scrcpy-GUI上有线无线都能连接上，投屏都失败。而在QTscrcpy上无线有线都能投屏成功。谢谢。

**Comment by Tomotoes** [comment]
@dreamcastddr @chengwerit 
如果命令行打不开设备的话, gui 软件是无法打开设备的.
gui 软件是命令行的可视化, 也仅此而已.

**Comment by Fiber-Five** [comment]
> 我在Mac上也出现了这个问题，但是直接使用scrcpy的命令是可以正常投屏的，如果是权限问题的话，该如何设置scrcpy-gui的权限呢

我在Mac上也出现了同样的问题，提示成功，但没有投屏画面，命令可以

**Comment by Tomotoes** [comment]
> > 我在Mac上也出现了这个问题，但是直接使用scrcpy的命令是可以正常投屏的，如果是权限问题的话，该如何设置scrcpy-gui的权限呢
> 
> 我在Mac上也出现了同样的问题，提示成功，但没有投屏画面，命令可以

抱歉, 我除了 windows 没有其他终端测试, 您可以 clone 下项目, rebuild下, 问题会解决.

**Comment by stoneyu001** [comment]
我也是相同问题，我是下载了最新的scrcpy 1.24 然后在环境变量里重新配置就好了，不知道我们问题是不是一样
