### ISSUE TITLE
无线连接失败

### ISSUE THREAD

**Issue by b99-ginagod** [Tomotoes/scrcpy-gui#45]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型：华为荣耀magic2
2. 系统信息：安卓10，magic ui 3.0.0
3. scrcpy 版本：1.10
4. 是否可以使用 scrcpy 在命令行 打开设备：是
5. 出错信息：开启无线连接失败

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by Tomotoes** [comment]
请将您的ip 设置成静态ip,再来尝试.
