### ISSUE TITLE
ctrl+o之后，返回桌面只有桌面背景，没有图标

### ISSUE THREAD

**Issue by bwsnb** [Tomotoes/scrcpy-gui#47]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型
红米note k20 pro 12G 256G

2. 系统信息
安卓10

3. scrcpy 版本
1.12.1

4. 是否可以使用 scrcpy 在命令行 打开设备
可以
5. 出错信息
ctrl+o关闭手机屏后，手机当前显示的画面是正常的。 按home（鼠标中键），返回桌面后只有桌面背景，没有任何图标。导航栏只有信号图标和电池图标

**Comment by genglongsir** [comment]
我是小米9稳定版,我的情况和你一样,ctrl+o后,只显示桌面,不显示图标

**Comment by Tomotoes** [comment]
建议关掉 开发者选项中的 `miui`调试 进行尝试.
