### ISSUE TITLE
显示连接成功但未出现界面

### ISSUE THREAD

**Issue by xiaoxuan-yu** [Tomotoes/scrcpy-gui#48]
## 前置需求
可全局使用 scrcpy adb 命令
## 所需信息
1. 手机类型
华为P30 pro
2. 系统信息
Android 10 EMUI 10.0.0
3. scrcpy 版本
1.10
4. 是否可以使用 scrcpy 在命令行 打开设备
是
5. 出错信息
![图片](https://user-images.githubusercontent.com/55308316/76674553-c086c880-65eb-11ea-9e90-d4290307cada.png)

**Comment by qiaozyqzy** [comment]
你尝试一下修改分辨率，
[经常问的问题](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#i-get-an-error-could-not-open-video-stream)

**Comment by Tomotoes** [comment]
建议加一下qq群, issue 我没有时间管理.
