### ISSUE TITLE
Electron Security Warning (Insecure Content-Security-Policy) 

### ISSUE THREAD

**Issue by svinothkumaryoung** [Tomotoes/scrcpy-gui#49]
Im getting this error please help to short out this issue.Thanks in advance

1. Mobile phone information: Redmi 6A
2. System information:   windows 10 64bit
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message "This renderer process has either no Content Security Policy set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks."

**Comment by Tomotoes** [comment]
It should be a problem of your device, please open the debugging option.
