### ISSUE TITLE
Don't work the software

### ISSUE THREAD

**Issue by Paoloqu1610** [Tomotoes/scrcpy-gui#50]
I have a problem, 1)-2) my devide is Xiaomi Mi 8, Android 10, Miui 11. 3) the scrcpy versione is 1.0.0.  4) yes,  Is it possible to open the device on the command line using scrcpy, using adb. 5) when write ip address xxx:xx:xx:x:5555, it's give me error "开启无线连接失败", i tried both wifi and USB cable. Thank you

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by Tomotoes** [comment]
Is the ip on your phone a static ip? 
Can u connect wirelessly using scrcpy?

**Comment by Paoloqu1610** [comment]
> L'ip sul tuo telefono è un ip statico?
> Puoi connetterti in modalità wireless usando scrcpy?

first of all thanks for the quick reply. for ip address it changes every time I connect the wifi or it changes every time I log in with the mobile network. I was unable to use wirelessly or adb. Thanks
![Screenshot (2)](https://user-images.githubusercontent.com/63109786/78424317-083dc480-766d-11ea-9cfb-7df583b17560.png)
![Screenshot (3)](https://user-images.githubusercontent.com/63109786/78424318-0a078800-766d-11ea-9dd7-d32deae05202.png)

**Comment by Tomotoes** [comment]
One thing to explain, this project is just scrcpy window software. If you ca n’t connect to the device from the command line, then the GUI software can’t do it.
It is recommended that you use a static IP and try it on the command line.
