### ISSUE TITLE
关闭屏幕的话就无法电脑上控制手机

### ISSUE THREAD

**Issue by sc962** [Tomotoes/scrcpy-gui#51]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. MIUI11
2. WIN10 64
3. 1.0.0
4. 可以
5. 只要选中打开镜像时关闭屏幕就会无法控制，只能投屏。隔壁的Qtscrcpy就可以，但是它那个又无法wifi连接。

**Comment by Tomotoes** [comment]
逻辑是这样的, 隔壁的 qtscrcpy 我不了解. 
如果你觉得麻烦, 可以设置一下不锁屏操作 :)
