### ISSUE TITLE
Scrcpy可以用，GUI提示错误

### ISSUE THREAD

**Issue by zqguang3708** [Tomotoes/scrcpy-gui#53]
#所需信息
1. 红米note7
2. win10 ltsc
3. scrcpy 1.0.0
4. Scrcpy可以正常使用
5. 打开失败,请您仔细查阅帮助文档

这个应该怎么排除问题

**Comment by Tomotoes** [comment]
您是无线还是有线啊? 

如果是无线, 请确保静态ip, ip正确.

既然命令行可以打开, 那应该就是权限问题了, 建议使用管理员模式打开软件再试一次.

**Comment by zqguang3708** [comment]
> 您是无线还是有线啊?
> 
> 如果是无线, 请确保静态ip, ip正确.
> 
> 既然命令行可以打开, 那应该就是权限问题了, 建议使用管理员模式打开软件再试一次.

开发者你好，我用的是有线。
adb devices可以列出设备，scrcpy可以正常使用，这次以管理员身份运行scrcpy-GUI依然显示“打开失败,请您仔细查阅帮助文档”
系统版本为LTSC 17763.1158。
很是奇怪QAQ

**Comment by Tomotoes** [comment]
会不会是窗口上的配置 与 scrcpy 的版本不兼容。

**Comment by Tomotoes** [comment]
> > 您是无线还是有线啊?
> > 如果是无线, 请确保静态ip, ip正确.
> > 既然命令行可以打开, 那应该就是权限问题了, 建议使用管理员模式打开软件再试一次.
> 
> 开发者你好，我用的是有线。
> adb devices可以列出设备，scrcpy可以正常使用，这次以管理员身份运行scrcpy-GUI依然显示“打开失败,请您仔细查阅帮助文档”
> 系统版本为LTSC 17763.1158。
> 很是奇怪QAQ

建议使用 软件自带的 scrcpy 版本试试。

呃。。

**Comment by zqguang3708** [comment]
> > > 您是无线还是有线啊?
> > > 如果是无线, 请确保静态ip, ip正确.
> > > 既然命令行可以打开, 那应该就是权限问题了, 建议使用管理员模式打开软件再试一次.
> > 
> > 
> > 开发者你好，我用的是有线。
> > adb devices可以列出设备，scrcpy可以正常使用，这次以管理员身份运行scrcpy-GUI依然显示“打开失败,请您仔细查阅帮助文档”
> > 系统版本为LTSC 17763.1158。
> > 很是奇怪QAQ
> 
> 建议使用 软件自带的 scrcpy 版本试试。
> 
> 呃。。

scrcpy-win64-v1.10.zip (SHA-256: 95de34575d873c7e95dfcfb5e74d0f6af4f70b2a5bc6fde0f48d1a05480e3a44)
使用这个scrcpy可以正常使用。
窗口上的配置，唔我都试了一遍，没啥太大影响QAQ
