### ISSUE TITLE
设备识别时出现的bug

### ISSUE THREAD

**Issue by ZzzzzzzSkyward** [Tomotoes/scrcpy-gui#54]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型
华为Nova 5i  
Android 10  
2. 系统信息
Win10x64，热点、usb一起连接手机  
3. scrcpy 版本
1.13  
4. 是否可以使用 scrcpy 在命令行 打开设备
可以  
5. 出错信息
如图所示，每隔约1秒出现emulator5554，之后消失。打开第一个镜像后，其状态仍然是断开连接。  
![图片](https://user-images.githubusercontent.com/55184223/81629647-32399200-9436-11ea-806a-56964711390b.png)

**Comment by Tomotoes** [comment]
会不会是数据线的问题, 为什么每隔一秒就消失...

**Comment by Tomotoes** [comment]
您可以在命令行模式下多尝试尝试, 如果问题依旧存在, 那就不是gui 软件的问题了.

**Comment by ZzzzzzzSkyward** [comment]
> 
> 
> 您可以在命令行模式下多尝试尝试, 如果问题依旧存在, 那就不是gui 软件的问题了.

已经确认没有问题了，可能我上次没连接(adb connect ...)
