### ISSUE TITLE
ubuntu 18.06 GUI白屏

### ISSUE THREAD

**Issue by emptywall** [Tomotoes/scrcpy-gui#57]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型
MI9
2. 系统信息
ubuntu 18.06
3. scrcpy 版本
1.14
4. 是否可以使用 scrcpy 在命令行 打开设备
可以
5. 出错信息
命令行启动GUI没有报错，但是GUI白屏无法使用

**Comment by Tomotoes** [comment]
抱歉, linux 等一些其他终端, 我暂时没有测试平台, 你可以clone 下项目, rebuild 下.
