### ISSUE TITLE
Include sndcpy? (Audio forwarder complementing scrcpy)

### ISSUE THREAD

**Issue by BanCrash** [Tomotoes/scrcpy-gui#58]
Hello, another user creates an audio forwarder that can complement scrpy. So I think could be useful that this gui combines scrcpy and sndcpy to have a complete casting on the pc of the mobile phone.

Right now it's still on WIP I think, so maybe it's not ready to be included yet, but I wanted to let you know just in case you want to add it on the future.

The link is this: https://github.com/rom1v/sndcpy

Regards and thanks you for developing and sharing this tool!

**Comment by Tomotoes** [comment]
Thank you for your proposal and approval. I have added it to the todo list. 
If you combine scrcpy with sndcpy as you said, it must be a wonderful thing.
I believe the scrcpy author will try it, just wait at this stage.

**Comment by BanCrash** [comment]
Perfect! :smile:
