### ISSUE TITLE
当配置最大帧率的时候打开镜像会报错，设置为默认值0的时候可以正常打开

### ISSUE THREAD

**Issue by Wangenrui** [Tomotoes/scrcpy-gui#59]
![image](https://user-images.githubusercontent.com/33220739/84480388-0cb6d700-acc7-11ea-9e21-5b63cf54c878.png)
当配置最大帧率的时候打开镜像会报错，设置为默认值0的时候可以正常打开

**Comment by Tomotoes** [comment]
请检查 scrcpy 版本是否为最新版.
