### ISSUE TITLE
能否调用输入法的相关接口

### ISSUE THREAD

**Issue by lians0** [Tomotoes/scrcpy-gui#6]
用电脑的键盘也能打 汉字

**Comment by tjsky** [comment]
感觉需要把电脑键盘模拟成OTG设备或者蓝牙设备。就像那些安卓模拟器做的那样。

PS：如果你想凑合，可以用搜狗输入法。那个可以直接用电脑键盘打字。

只不过因为电脑键盘没有被识别为外接键盘，所以候选词没有翻页键。

目前大部分情况下凑合够用。

**Comment by Tomotoes** [comment]
我用我朋友的设备就可以打字..

用我的就不行..

我感觉是输入法的问题..

**Comment by tjsky** [comment]
@Tomotoes 
我测试的是，百度输入法和QQ拼音输入法都不行，搜狗输入法可以，但是不完善。
安卓默认的快捷键无法用，shift切换中英文，+_翻页，大小写锁定，小键盘输入数字。这些都木有。
输入法并不知道外接实体键盘的存在。
