### ISSUE TITLE
关于matepad pro使用无线连接的问题

### ISSUE THREAD

**Issue by Wyler-Yue** [Tomotoes/scrcpy-gui#61]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型：matepad pro
2. 系统信息：EMUI10.1.0.136
3. scrcpy 版本：V1.10
4. 是否可以使用 scrcpy 在命令行 打开设备：有线能使用
5. 出错信息：无线连接无效

**Comment by Tomotoes** [comment]
在有线的情况下， 输入 ip， 配置一下无线， 之后再 拔掉数据线 尝试无线连接。

**Comment by Wyler-Yue** [comment]
> 在有线的情况下， 输入 ip， 配置一下无线， 之后再 拔掉数据线 尝试无线连接。

![image](https://user-images.githubusercontent.com/56312222/85708095-68954d00-b716-11ea-8578-cf2f7941415d.png)
还是没有成功，而且出现了新的情况
