### ISSUE TITLE
不使用管理员权限运行则无法打开无线镜像

### ISSUE THREAD

**Issue by FallenXtar** [Tomotoes/scrcpy-gui#62]
1. 手机类型
 Redmi K20 Pro 8+256版， with MIUI 12 stable

2. 系统信息
Windows 10 专业教育版 1909 18363.900

3. scrcpy 版本 

``` powershell
PS C:\> scrcpy -v
scrcpy 1.14

dependencies:
 - SDL 2.0.12
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100
```

4. 是否可以使用 scrcpy 在命令行 打开设备
是，参见前一条

5. 出错信息
如果不使用管理员权限运行则无法打开无线镜像

**Comment by Tomotoes** [comment]
那就右键快捷方式, 设置 一直使用 管理员 打开该软件, 再试试.
