### ISSUE TITLE
勾选关闭锁屏之后无法打开设备

### ISSUE THREAD

**Issue by amalika** [Tomotoes/scrcpy-gui#63]
## 前置需求
可全局使用 scrcpy adb 命令
C:\Users\11301>scrcpy -v
scrcpy 1.12.1

dependencies:
 - SDL 2.0.10
 - libavcodec 58.54.100
 - libavformat 58.29.100
 - libavutil 56.31.100
## 所需信息
1. 手机类型
  小米Mix2 小米 note 2 小米 Mi6
2. 系统信息
  
3. scrcpy 版本
  Scrcpy-gui

name: scrcpy-gui
version: 1.5.1
homepage: https://github.com/Tomotoes/scrcpy-gui
author: SimonMa 
license: Apache-2.0
description: ✨ A simple & beautiful GUI application for scrcpy
node: 8.9.3
chrome: 61.0.3163.100
electron: 2.0.18
4. 是否可以使用 scrcpy 在命令行 打开设备
5. 出错信息
  
![image](https://user-images.githubusercontent.com/21135081/86475589-8e0a0280-bd77-11ea-8991-1668d612caa2.png)

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by Tomotoes** [comment]
请使用最新版本的scrcpy, 再来试试.
