### ISSUE TITLE
是否支持同时镜像多设备？

### ISSUE THREAD

**Issue by phoenixsky** [Tomotoes/scrcpy-gui#64]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型 多设备
2. 系统信息 mac 
3. scrcpy 版本  ：1.5.1
4. 是否可以使用 scrcpy 在命令行 打开设备 ：可以
5. 出错信息 只能同时打开一个

是否同时打开多个设备？
通过命令行指定端口是可以打开的。 GUI无法同时打开多个镜像

**Comment by shiwf** [comment]
可以修改src/main/scrcpy/index.js，为args增加一个--port参数，传入一个随机端口号，就可以支持同时打开多个设备。

**Comment by Tomotoes** [comment]
支持的, 在 GUI 页面同时勾选多个设备 点击打开即可.

**Comment by qcks** [comment]
Windows 使用有线方式连接多台设备报错 adb push returned with value 1
