### ISSUE TITLE
文件存储

### ISSUE THREAD

**Issue by yks176175** [Tomotoes/scrcpy-gui#68]
## 需求
自定义拖放文件位置

有时文件名会乱码
 在scrcpy 中设置的文件存储位置tomotoes不起作用😗（根目录sdcard又不是不能用）

**Comment by Tomotoes** [comment]
`tomotoes` 只是个例子, 需要你再次修改...

建议补充一下 .github/ISSUE_TEMPLATE 所需的信息.
