### ISSUE TITLE
Win10安装15.1后界面显示异常

### ISSUE THREAD

**Issue by qiaozyqzy** [Tomotoes/scrcpy-gui#71]
## Win10安装15.1后界面显示异常
如图：
![image](https://user-images.githubusercontent.com/47310135/92937447-ec411900-f47d-11ea-8b8b-ed428de3b87e.png)

电脑为：Windows 10家庭中文版-1909

**Comment by chk141** [comment]
我猜你动了语言文件吧，别折腾了，你又搞不定，把语言文件补上就好了

**Comment by qiaozyqzy** [comment]
> 我猜你动了语言文件吧，别折腾了，你又搞不定，把语言文件补上就好了

不，我没有动，至少主观上没动，，，我是在15.0的基础上安装的15.1。现在我又装回15.0了，显示是正常的。
