### ISSUE TITLE
使用中，屏幕亮起问题

### ISSUE THREAD

**Issue by qingfengfenga** [Tomotoes/scrcpy-gui#77]
链接过程中，勾选关闭屏幕，中途打开手机屏幕的话，设置的关闭屏幕就失效了，只能重新链接。要不手机屏幕就会跟着操作亮起；

**Comment by Tomotoes** [comment]
> 链接过程中，勾选关闭屏幕，中途打开手机屏幕的话，设置的关闭屏幕就失效了，只能重新链接。要不手机屏幕就会跟着操作亮起；

您说的需求, 只能通过重启 scrcpy 来解决, 因为 您打开手机屏幕 是没有事件钩子的..
您打开屏幕后 继续想一直关闭屏幕, 您可以查阅 adb 文档, 会有相应的指令.
