### ISSUE TITLE
ctrl+o快捷键失效，按完画面以后会卡住

### ISSUE THREAD

**Issue by b99-ginagod** [Tomotoes/scrcpy-gui#78]
## 前置需求
可全局使用 scrcpy adb 命令

## 所需信息
1. 手机类型：小米10Pro
2. 系统信息： MIUI12.0.4
3. scrcpy 版本:1.5.1
4. 是否可以使用 scrcpy 在命令行 打开设备：是
5. 出错信息：
无法使用Ctrl+O/S等快捷键，且按完Ctrl+O之后，手机由原本的电脑可投屏+可控制状态变为仅可投屏，不可控制。

## Pre-requirements
Can use the scrcpy adb command globally

## Required information
1. Mobile phone information
2. System information
3. scrcpy version
4. Is it possible to open the device on the command line using scrcpy?
5. Error message

**Comment by Tomotoes** [comment]
您可以试着升级下 scrcpy 的版本 看看.

**Comment by b99-ginagod** [comment]
你好，已经是最新版本了。



---原始邮件---
发件人: "SimonAking"<notifications@github.com&gt;
发送时间: 2020年10月13日(周二) 上午10:52
收件人: "Tomotoes/scrcpy-gui"<scrcpy-gui@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"b99-ginagod"<784760213@qq.com&gt;;
主题: Re: [Tomotoes/scrcpy-gui] ctrl+o快捷键失效，按完画面以后会卡住 (#78)




 
您可以试着升级下 scrcpy 的版本 看看.
