### ISSUE TITLE
初始化和剪切屏幕功能怎么使用？

### ISSUE THREAD

**Issue by Ice-Castellan** [Tomotoes/scrcpy-gui#79]
## 前置需求
想请问下，初始化和剪切屏幕是怎么使用，不是很理解提示信息！
## 所需信息
1. 手机类型：红米K305G
2. 系统信息：MIUI12
3. scrcpy 版本：1.5.1
4. 是否可以使用 scrcpy 在命令行 打开设备:可以
5. 出错信息：默认位置并不是下图这样，是一般大小的图，下图是想要的效果
![微信截图_20201011220509](https://user-images.githubusercontent.com/58472183/95680787-97c0c300-0c0e-11eb-8ff7-5ac97b07bc9d.png)

**Comment by Tomotoes** [comment]
这个您打开后, 拖过去不就行了嘛...
