### ISSUE TITLE
快捷键失灵，另外可否增加绑定快捷键功能？可以用来打游戏了，延时非常低。

### ISSUE THREAD

**Issue by bim-hmc** [Tomotoes/scrcpy-gui#81]
## 所需信息
1. 手机类型 华为荣耀10  
2. 系统信息  win7 x64
3. scrcpy 版本 1.16
4. 是否可以使用 scrcpy 在命令行 打开设备 正常
5. 出错信息   无法使用快捷键，均不好使。
另外能否增加屏幕绑定按钮？就能打游戏了。

![微信图片_20201026154311](https://user-images.githubusercontent.com/21001606/97145890-e4c19f00-17a1-11eb-8962-0173582e008f.png)

**Comment by Tomotoes** [comment]
暂不支持~
