### ISSUE TITLE
How to change english version

### ISSUE THREAD

**Issue by kibua20** [Tomotoes/scrcpy-gui#82]
scrcpy-gui is a great tools. 

I have installed scrcpy-gui on Ubuntu 20.04 by the deb file shared on https://github.com/Tomotoes/scrcpy-gui/releases.
It works well, but the all characters on the app is  Chinese.  
How to change to English version?

Regards,
kibua20

**Comment by Tomotoes** [comment]
![image](https://user-images.githubusercontent.com/32236122/97827464-5a2bf300-1cff-11eb-8838-9a6aec430fa2.png)

**Comment by Tomotoes** [comment]
> scrcpy-gui is a great tools.
> 
> I have installed scrcpy-gui on Ubuntu 20.04 by the deb file shared on [Tomotoes/scrcpy-gui/releases](https://github.com/Tomotoes/scrcpy-gui/releases).
> It works well, but the all characters on the app is Chinese.
> How to change to English version?
> 
> Regards,
> kibua20
Haha, thank you for your support~
