### ISSUE TITLE
测试了一下，红米K20开启失败 

### ISSUE THREAD

**Issue by teeth010hhu** [Tomotoes/scrcpy-gui#9]
用命令行打开（有线和无线）没有任何问题，但是通过软件打开时提示连接成功，但是就是没有画面显示（有线与无线），是不是我配置有问题呀？

**Comment by Tomotoes** [comment]
我也是用小米软件测试的, 没有问题~ 
我觉得可能是你运行程序的权限问题, 最好使用管理员运行软件

我软件后台会开启一个进程来执行 scrcpy 命令, 如果权限不够 可能无法打开新的进程~

**Comment by fanfan2018** [comment]
我也k20pro试了一下，开启前关掉那个镜像录屏保存设置就能开了，打开镜像录屏好像投屏不出来。
